# Query with arguments

query GET_USER_WITH_ID {
  user(id: "602") {
    id
    firstName
    lastName
    userName
  }
}

query GET_POST_WITH_ID {
  post(id: "602") {
    id
    title
    body
  }
}
